<?php
    $url = "{$this->baseUrl()}/admin/commission/chitscommissiongrid";
?>
<script type="text/javascript">
    
$(document).ready(function(){
    $(document).pngFix( );
    $("#flexme").flexigrid({
       url: '<?=$url?>',
       dataType: 'json',
       colModel : [
                {display: 'No', name : 'No', width : 20, sortable : true, align: 'left'},
                {display: 'Chits Code', name : 'chits_code', width : 120, sortable : true, align: 'left'},
		{display: 'Amount', name : 'amount', width : 50, sortable : true, align: 'left'},                
                {display: 'Options', name : 'options', width : 130, sortable : true, align: 'left'}            
           ],
       buttons : [
            {name: 'Add Commission', bclass: 'Add', onpress : test},               
            {separator: true}
            ],
        searchitems : [
            {display: 'Chits Code', name : 'first_name'}
            ],
       sortname: "chits_code",
       sortorder: "asc",
       usepager: true,
       title: 'Chits Commission',
       useRp: true,
        rp: 10,
        onSubmit: addFormData,
        showTableToggleBtn: true,
        width: 500,
        height: 200
    });
     $('#chitCommissionSearch').submit(function (){
        $('#flexme').flexOptions({newp: 1}).flexReload();
        return false;
    })
});
function test(com, grid) {
    if (com == 'Add Commission') {               
                location.href='<?php echo $this->baseUrl() ?>/admin/commission/addcommission';
        } 
}
function addFormData(){
//passing a form object to serializeArray will get the valid data from all the objects, but, if the you pass a non-form object, you have to specify the input elements that the data will come from
var dt = $('#chitCommissionSearch').serializeArray();
$("#flexme").flexOptions({params: dt});
return true;
}

</script>
<div id="page-heading">
		<h1>Chits Commissions</h1>
	</div>
<?php echo $this->form; ?>
<table id="flexme"></table>