

<?php
    $url = "{$this->baseUrl()}/admin/commission/detailgrid/agent/{$this->agent_id}";
?>
<script type="text/javascript">
    
$(document).ready(function(){
    $(document).pngFix( );
    $("#flexme").flexigrid({
       url: '<?=$url?>',
       dataType: 'json',
       colModel : [
                {display: 'No', name : 'No', width : 20, sortable : true, align: 'left'},
                {display: 'Chital', name : 'Chital', width : 120, sortable : true, align: 'left'},
                {display: 'Chit', name : 'chit', width : 50, sortable : true, align: 'left'},
                {display: 'Installment', name : 'installment', width : 50, sortable : true, align: 'left'},
                {display: 'Date', name : 'payed_date', width : 50, sortable : true, align: 'left'},
                {display: 'Amount', name : 'Amount', width : 50, sortable : true, align: 'left'},
                {display: 'Current Status', name : 'Amount', width : 50, sortable : true, align: 'left'},
                {display: 'Options', name : 'options', width : 130, sortable : true, align: 'left'}          
           ],
        searchitems : [
            {display: 'Name', name : 'first_name'}
            ],
       sortname: "first_name",
       sortorder: "asc",
       usepager: true,
       title: 'Employees',
       useRp: true,
        rp: 10,
        onSubmit: addFormData,
        showTableToggleBtn: true,
        width: 700,
        height: 200
    });
     $('#agentCommissionSearch').submit(function (){
        $('#flexme').flexOptions({newp: 1}).flexReload();
        return false;
    })
});
function test(com, grid) {
    var id = $('.trSelected td div:first-child').html();  
    var designation = $('.trSelected td div:nth-child(2)').html();  
    alert(id+'<>'+designation);
}
function addFormData(){
//passing a form object to serializeArray will get the valid data from all the objects, but, if the you pass a non-form object, you have to specify the input elements that the data will come from
var dt = $('#agentCommissionSearch').serializeArray();
$("#flexme").flexOptions({params: dt});
return true;
}

</script>
<div id="page-heading">
		<h1>Commission Details</h1>
	</div>
<?php echo $this->form; ?>
<table id="flexme"></table>
