<script type="text/javascript">
function changemenu(id) {
    $('.hidediv').hide();
    $('#' + id).show();
}
</script>

<table width="100%" cellspacing="0" cellpadding="0" border="0" id="content-table">
	<tbody><tr>
		<th class="sized" rowspan="3"><img width="20" height="300" alt="" src="images/shared/side_shadowleft.jpg"></th>
		<th class="topleft"></th>
		<td id="tbl-border-top">&nbsp;</td>
		<th class="topright"></th>
		<th class="sized" rowspan="3"><img width="20" height="300" alt="" src="images/shared/side_shadowright.jpg"></th>
	</tr>
	<tr>
		<td id="tbl-border-left"></td>
		<td>
		<div id="content-table-inner">
		
			<!--  start table-content  -->
			<div id="table-content">
				<!--  start product-table ..................................................................................... -->
				
				<table width="100%" cellspacing="0" cellpadding="0" border="0" id="product-table">
				<tbody><tr>
					<th class="table-header-repeat line-left minwidth-1"><a href="#" onclick="javascript: changemenu('datewise')">Date Wise</a></th>
					<th class="table-header-repeat line-left minwidth-1"><a href="#" onclick="javascript: changemenu('chitwise')">chit Wise</a></th>
					<th class="table-header-repeat line-left"><a href="#" onclick="javascript: changemenu('agentwise')">Agent Wise</a></th>
				</tr>
                                
				<tr>
                                    <td colspan="4" align="center">
                                        <div id="content-table-inner">
                                        <!--date wise report -->
<div id="datewise" class="hidediv">
    <form method="post" action="<?php echo $this->baseUrl(); ?>/admin/report/datewise">
    <table class="data">
        <tr>
             <th colspan="2">Date wise report</th>
         </tr>

        <tr class="odd">
            <td>Start date</td><td><input type="text" name="start_date" class="datepicker"/></td>
        </tr>
        <tr>
            <td>End date</td><td><input type="text" name="end_date" class="datepicker"/></td>
        </tr>
        <tr class="odd">
            <td></td><td><input type="submit" value="submit"/></td>
        </tr>

    </table>
    </form>
</div>

<!--chit wise report -->
<div id="chitwise" class="hidediv" style="display:none">
    
    <table class="data">
         <tr class="odd">
             <td colspan="4"><h1>Chits Wise Report</h1></td>
             <td><h4>From installment :</h4><input type="text" name="start_installment" value="1"></td>
             <td><h4>To installment :</h4><input type="text" name="end_installment" value="1"> </td>
         </tr>
        <tr>
            <th>Chits code</th>
            <th>Installments</th>
            <th>Sala </th>
            <th>Current Installment</th>
            <th>Next chit date</th>
            <th>amount</th>
        </tr>
        
        <?php 
        foreach($this->chitswise as $chitwise_data):
        ?>
        <tr class="<?php print (!$this->getHelper('PartialLoop')->view->altrow ^= 1) ? 'odd' : '';?>">
             <td>
        <a href="<?php echo $this->baseUrl() ?>/admin/report/chitwise/chit/<?php echo $chitwise_data['chit_id'];?>/start/1/end/<?php echo $chitwise_data['current_installment'];?>"> 
           <?php echo $chitwise_data['chit_code']; ?>
             </a></td>
             <td><?php echo $chitwise_data['period']; ?></td>
             <td><?php echo $chitwise_data['sala']; ?></td>
             <td><?php echo $chitwise_data['current_installment']; ?></td>
             <td><?php echo date('d-M-Y',$chitwise_data['next_chit_date']); ?></td>
             <td><?php echo $chitwise_data['installment_amount']; ?></td>
         </tr>
         <?php 
         endforeach;
         ?>
    </table>
</div>

<!--agent wise report -->
<div id="agentwise" class="hidediv" style="display:none">
    
    <table class="data">
         <tr class="odd">
             <td colspan="2"><h1>Agent wise report</h1></td>
         </tr>
        <tr>
            <th>Name</th>
            <th>mobile</th>
        </tr>
        
        <?php 
        foreach($this->agentswise as $agentwise_data):
        ?>
         <tr class="<?php print (!$this->getHelper('PartialLoop')->view->altrow ^= 1) ? 'odd' : '';?>">
             <td>
                 <a href="<?php echo $this->baseUrl() ?>/admin/report/agentwise/agent/<?php echo $agentwise_data['employee_id'];?>/start/2010-10-05/end/<?php echo date('Y-m-d', time());?>"> 
    <?php echo $agentwise_data['first_name'] . ' ' . $agentwise_data['last_name'] ; ?></a>
             </td>
             <td><?php echo $agentwise_data['mobile']; ?></td>             
         </tr>
         <?php 
         endforeach;
         ?>
    </table>
    
</div><div class="clear"></div>
                                        </div>
                                    </td>
				</tr>
                                
				
				</tbody></table>
				<!--  end product-table................................... --> 
				
			</div>
                            <!--  end content-table  -->
		
			
			
			<!--  start paging..................................................... -->
			
			<!--  end paging................ -->
			
			<div class="clear"></div>
		 
		</div>
		<!--  end content-table-inner ............................................END  -->
		</td>
		<td id="tbl-border-right"></td>
	</tr>
	<tr>
		<th class="sized bottomleft"></th>
		<td id="tbl-border-bottom">&nbsp;</td>
		<th class="sized bottomright"></th>
	</tr>
	</tbody></table>
