<html>
<head>
    <style type="text/css">
        @media screen {

        body {
             background-color: #778899;
             color: #373832;
             font: 700 16px Arial, Sans-Serif;
        } }

        @media print {
        .no-print { display: none; }
        body { 
             background: #fff;  
             color: #000000;
             font: 500 13px 'Lucida Console', 'courier new', monospace; 
        } }
    </style>
 
    <script type="text/javascript"> 
        function printMe() {
            document.getElementById('print').innerHTML = '';
            window.print();  
        } 
    </script>
</head>
<body>
<table border="3" cellspacing="5" cellpadding="5">
 <tr>
     <th>Chits code</th>
     <th>Token</th>
     <th>Customer</th>
     <th>Mobile</th>
     <th>collection type</th>
     <?php 
    $columns = array();
    $pending_per_installment = array();
    $j = 0;
    $head_from_date = $from_date = strtotime($this->from_date);
    $to_date = strtotime($this->to_date);
    while( $head_from_date <= $to_date)
    {
         echo '<th>' . date('M Y',  $head_from_date) . '</th>';         
         $head_from_date = strtotime("+1 month",  $head_from_date);
    }          
    ?>
    <th>Pending</th><th>Amount-paid</th>
    </tr>
    <?php       
    $total_pending  = 0;
    $total_paid     = 0;
    foreach($this->data as $data):          
    ?>
         <tr class="<?php print (!$this->getHelper('PartialLoop')->view->altrow ^= 1) ? 'odd' : '';?>">
         <td><?php echo $data['user_details']['chit_code']; ?></td>
         <td><?php echo $data['user_details']['token']; ?></td>
         <td><?php echo $data['user_details']['first_name'].' '.$data['user_details']['last_name']; ?></td>
         <td><?php echo $data['user_details']['mobile']; ?></td>
         <td><?php echo ($data['user_details']['collection_type']==1)?'Monthly':'Daily'; ?></td>
         <?php 
         $paid = 0;
         $pending = 0;  
         $begining_flag = true;
         foreach($data['installments_details'] as $installment_data):
              $installment_date = $installment_data['installment_date']; 
              $month_key = date('Ym', $installment_data['installment_date']);
              
             //for insert blank td for non value 
              if($begining_flag){
                  $td_from_date = $from_date;
                  while($td_from_date <= $installment_date )
                  {
                     echo '<td>0</td>';     
                     $td_from_date = strtotime("+1 month", $td_from_date);                  
                  }
              }  
             $begining_flag = false;
            //calclulating amount pending and paid
             $pending += $installment_data['amount_to_pay'];; 
             $paid    += $installment_data['amount_received'];
       
             if($installment_date >= $from_date && $installment_date <= $to_date){
                 //per installment pending
                 if(!isset($pending_per_month[$month_key]))
                     $pending_per_month[$month_key] = 0;

                echo'<td>';
                 if($installment_data['payment_status']== 'C'){
                     echo date('d-m-Y',$installment_data['payed_date']);
                     $paid += $installment_data['amount'];
                 }elseif($installment_data['payment_status']== 'R'){            
                   echo date('d-m-y',$installment_data['payed_date']) . '<br>' . $installment_data['amount_to_pay'];
                    $pending_per_month[$month_key] += $installment_data['amount_to_pay'];
                 }else{
                    echo $installment_data['amount_to_pay'];     
                    $pending_per_month[$month_key] += $installment_data['amount_to_pay'];
                 }
                 echo'</td>';  
               }
           endforeach;        
           //for insert blank td for non value
           $td_installment_date = $installment_date;
            while($td_installment_date <= $to_date)
             {
                 echo '<td>0</td>';     
                 $td_installment_date = strtotime("+1 month", $td_installment_date);                  
             } 
           ?>
         <td><?php echo $pending; 
                $total_pending += $pending;
         ?></td><td><?php echo $paid; 
                $total_paid += $paid;
         ?></td>
     </tr>
    <?php 
endforeach;
    ?>
</tr>
<td colspan="5">Total</td>
<?php 
    $pending_from_date = $from_date;
    while ($pending_from_date <= $to_date)
    {
       echo'<td>'; 
       $pending_month_key = date('Ym', $pending_from_date);  
       echo (isset ($pending_per_month[$pending_month_key]))?$pending_per_month[$pending_month_key]:0;       
       $pending_from_date  = strtotime("+1 month",  $pending_from_date );
       echo'</td>';
    } 
 ?>
<td><?php echo $total_pending; ?></td>
<td><?php echo $total_paid; ?></td>
<td></td>
      </tr>
</table>
   
<div id="print">
    <input type="button" value="Print" onclick="printMe();" /> 
</div>

</body>
</html>

