<?php
    $url = "{$this->baseUrl()}/admin/prize/prizegrid";
?>
<script type="text/javascript">
    
$(document).ready(function(){
    $(document).pngFix( );
    $("#flexme").flexigrid({
       url: '<?=$url?>',
       dataType: 'json',
       colModel : [
               {display: 'No', name : 'id', width : 20, sortable : true, align: 'left'},
                {display: 'Chit code', name : 'chit_code', width : 50, sortable : true, align: 'left', formatter:test},		
                {display: 'Installment', name : 'installment', width : 50, sortable : true, align: 'left'},
                {display: 'Prize Type', name : 'prize_type', width : 50, sortable : true, align: 'left'},
                {display: 'Token', name : 'token', width : 50, sortable : true, align: 'left'},
                {display: 'First Name', name : 'first_name', width : 130, sortable : true, align: 'left'},
                {display: 'Prize Amount', name : 'prize_amount', width : 100, sortable : true, align: 'left'},
                {display: 'Payment Date', name : 'payment_date', width : 70, sortable : true, align: 'left'},
                {display: 'Status', name : 'status', width : 50, sortable : true, align: 'left'},
                {display: 'Options', name : 'options', width : 130, sortable : true, align: 'left'}        
           ],
        searchitems : [
            {display: 'Name', name : 'chit_code'}
            ],
       sortname: "chit_code",
       sortorder: "asc",
       usepager: true,
       title: 'Prize Management',
       useRp: true,
        rp: 10,
        onSubmit: addFormData,
        showTableToggleBtn: true,
        width: 800,
        height: 200
    });
     $('#prizeSearch').submit(function (){
        $('#flexme').flexOptions({newp: 1}).flexReload();
        return false;
    })
});
function test(com, grid) {
//    var id = $('.trSelected td div:first-child').html();  
//    var designation = $('.trSelected td div:nth-child(2)').html();  
//    alert(id+'<>'+designation);
}
function addFormData(){
//passing a form object to serializeArray will get the valid data from all the objects, but, if the you pass a non-form object, you have to specify the input elements that the data will come from
var dt = $('#prizeSearch').serializeArray();
$("#flexme").flexOptions({params: dt});
return true;
}
</script>
<div id="page-heading">
        <h1>Prize</h1>
</div>
<?php echo $this->form; ?>
<table id="flexme"></table>