<script type="text/javascript">
    function getUser()
    {
        var customer_id = $('.styledselect option:selected').val();
        $.ajax({
                type: "POST",
                url: '<?php echo $this->baseUrl() ?>/admin/prize/getuser',
                data: "ajax=true&customer_id="+customer_id,
                success: function(msg){
                    //alert(msg);
                    $('#customer_name').val(msg);
                    $('#customer_id').val(customer_id);
                }
        });
    }
</script>
<div id="page-heading"><h1>Add price</h1></div>


<table width="100%" cellspacing="0" cellpadding="0" border="0" id="content-table">
<tbody><tr>
	<th class="sized" rowspan="3"><img width="20" height="300" alt="" src="images/shared/side_shadowleft.jpg"></th>
	<th class="topleft"></th>
	<td id="tbl-border-top">&nbsp;</td>
	<th class="topright"></th>
	<th class="sized" rowspan="3"><img width="20" height="300" alt="" src="images/shared/side_shadowright.jpg"></th>
</tr>
<tr>
	<td id="tbl-border-left"></td>
	<td>
	<!--  start content-table-inner -->
	<div id="content-table-inner">
	
	<?php
echo $this->prizeForm;

?>
 
<div class="clear"></div>
 

</div>
<!--  end content-table-inner  -->
</td>
<td id="tbl-border-right"></td>
</tr>
<tr>
	<th class="sized bottomleft"></th>
	<td id="tbl-border-bottom">&nbsp;</td>
	<th class="sized bottomright"></th>
</tr>
</tbody></table>

<div class="clear">&nbsp;</div>
