<table id="flex1" style="display:none"></table>
<script type="text/javascript">
    $("#flex1").flexigrid({
	url: '<?php echo $this->baseUrl() ?>/admin/bonus/detailsgrid/chit/' + <?=$this->chit_id?> + '/bonus/' + <?=$this->bonus?>,
	dataType: 'json',
	colModel : [
                {display: 'No', name : 'id', width : 20, sortable : true, align: 'left'},
		{display: 'Start Installment', name : 'start_installment', width : 50, sortable : true, align: 'left', formatter:testamal},		
                {display: 'End  Installment', name : 'end_installment', width : 120, sortable : true, align: 'left'},
		{display: 'Bonus amount', name : 'amount', width : 130, sortable : true, align: 'left'},
                {display: 'Options', name : 'options', width : 130, sortable : true, align: 'left'}
                ],
	buttons : [
            
		{name: 'Add Bonus', bclass: 'add', onpress : test},               		
		{separator: true}
		],
	searchitems : [
		{display: 'Chit code', name : 'chit_code'},
		{display: 'Code', name : 'chit_code', isdefault: true}
		],
	sortname: "chit_code",
	sortorder: "asc",
	usepager: true,
	title: 'Chits',
	useRp: true,
	rp: 15,
	showTableToggleBtn: true,
	width: 700,
	height: 200
});  
function testamal() {
    alert("here");
    return 'here';
}
$(document).ready(function(){
    $(document).pngFix( );
});
function test() {
    location.href='<?php echo $this->baseUrl() ?>/admin/bonus/add/chit_id/' + <?=$this->chit_id?> + '/bonus_type/' + <?=$this->bonus?>;
}
</script>