<?php
    $url = "{$this->baseUrl()}/admin/commission/commissiongrid";
?>
<script type="text/javascript">
    
$(document).ready(function(){
    $(document).pngFix( );
    $("#flexme").flexigrid({
       url: '<?=$url?>',
       dataType: 'json',
       colModel : [
                {display: 'No', name : 'No', width : 20, sortable : true, align: 'left'},
                {display: 'Name', name : 'agent', width : 120, sortable : true, align: 'left'},
		{display: 'Fine', name : 'fine', width : 50, sortable : true, align: 'left'},
                {display: 'On Hold', name : 'commission_hold', width : 50, sortable : true, align: 'left'},
                {display: 'Payed', name : 'payed', width : 50, sortable : true, align: 'left'},
                {display: 'Commission', name : 'commission', width : 50, sortable : true, align: 'left'},
                {display: 'Options', name : 'options', width : 130, sortable : true, align: 'left'}            
           ],
        searchitems : [
            {display: 'Name', name : 'first_name'}
            ],
       sortname: "agent_name",
       sortorder: "asc",
       usepager: true,
       title: 'Commission',
       useRp: true,
        rp: 10,
        onSubmit: addFormData,
        showTableToggleBtn: true,
        width: 700,
        height: 200
    });
     $('#commissionSearch').submit(function (){
        $('#flexme').flexOptions({newp: 1}).flexReload();
        return false;
    })
});
function test(com, grid) {
//    var id = $('.trSelected td div:first-child').html();  
//    var designation = $('.trSelected td div:nth-child(2)').html();  
//    alert(id+'<>'+designation);
}
function addFormData(){
//passing a form object to serializeArray will get the valid data from all the objects, but, if the you pass a non-form object, you have to specify the input elements that the data will come from
var dt = $('#commissionSearch').serializeArray();
$("#flexme").flexOptions({params: dt});
return true;
}

</script>
<div id="page-heading">
		<h1>Commissions</h1>
	</div>
<?php echo $this->form; ?>
<table id="flexme"></table>
