<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title></title>    
    <?php echo $this->headTitle() ?>
    <?php echo $this->headMeta() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
    <?php echo $this->headScript() ?>
<script>
    var baseUrl = '<?php echo $this->baseUrl() ?>';
</script>
<link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/flexigrid/css/flexigrid.css" type="text/css" />

<link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/css/screen.css" type="text/css" media="screen" />
<link rel="print stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>/css/print.css" media="print" />

<link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/themes/base/jquery.ui.all.css" media="screen" />

<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>/css/ddlevelsmenu-topbar.css" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>/css/ddlevelsmenu-base.css" />
<!--[if IE]>
<link rel="stylesheet" media="all" type="text/css" href="<?php echo $this->baseUrl() ?>/css/pro_dropline_ie.css" />
<![endif]-->

<!--  jquery core -->
<script src="<?php echo $this->baseUrl() ?>/js/jquery/jquery-1.4.1.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl() ?>/js/jquery/jquery.tooltip.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl() ?>/js/jquery.printElement.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl() ?>/flexigrid/js/flexigrid.js" type="text/javascript"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl() ?>/js/ddlevelsmenu.js"></script>
<script src="<?php echo $this->baseUrl() ?>/js/ui/jquery.ui.core.js"></script>
<script src="<?php echo $this->baseUrl() ?>/js/ui/jquery.ui.widget.js"></script>
<script src="<?php echo $this->baseUrl() ?>/js/ui/jquery.ui.datepicker.js"></script>

<!-- MUST BE THE LAST SCRIPT IN <HEAD></HEAD></HEAD> png fix -->
<script src="<?php echo $this->baseUrl() ?>/js/jquery/jquery.pngFix.pack.js" type="text/javascript"></script>

<script type="text/javascript">
$(document).ready(function(){ 
$(".datepicker").datepicker({
    dateFormat: 'yy-mm-dd'
});
$(".datepicker1").datepicker({
    dateFormat: 'yy-mm-dd',
    changeYear: true,
    yearRange: '-80:-10',
    defaultDate: '1990-01-01'
});
$(".datepicker").not('.dateEdit').datepicker('setDate', new Date());
});
</script>

</head>
<body> 

<!-- Start: page-top-outer -->
<div id="page-top-outer">    
    <!-- Start: page-top -->
    <div id="page-top">
        <!-- start logo -->
        <div id="logo">
            <h1>Chits</h1>
        </div>
        <!-- end logo -->
    </div>
    <!-- End: page-top -->
</div>
<!-- End: page-top-outer -->
	
<div class="clear">&nbsp;</div>
 
<!--  start nav-outer-repeat........ START -->
<div class="nav-outer-repeat"> 
    <!--  start nav-outer -->
    <div class="nav-outer"> 
        <!-- start nav-right -->
        <div id="nav-right">

            <div class="nav-divider">&nbsp;</div>
           <div> <?php echo $this->LoggedInAs($this->baseUrl()); ?></div>
            <div class="clear">&nbsp;</div>
        </div>
<script type="text/javascript">
    ddlevelsmenu.setup("ddtopmenubar", "topbar");
     //ddlevelsmenu.setup("mainmenuid", "topbar|sidebar");
</script>
        <!-- end nav-right -->
       <!--  start nav -->
       <?php 
           $auth = Zend_Auth::getInstance();
           $role = $auth->getIdentity()->role;
       ?>
    <div class="nav">
        <div id="ddtopmenubar" class="mattblackmenu">
            <ul>
                <li class="border-none">
                    <a href="<?php echo $this->baseUrl() ?>/admin/users/" class="on"><b>Users</b></a>
                </li>
                <?php if($role =='admin' || $role == 'super admin'){?>
                <li>
                    <a href="<?php echo $this->baseUrl() ?>/admin/chits" rel="ddsubmenu1"><b>Chits</b></a>   
                </li>
                <?php }?>
                <li>
                    <a rel="ddsubmenu2" href="<?php echo $this->baseUrl() ?>/admin/chitscollection"><b> Chits Collection</b></a>
                </li>
                <li>
                    <a rel="ddsubmenu3" href="<?php echo $this->baseUrl() ?>/admin/payment"><b>Bill Payment</b></a>
                </li>
                <li>
                    <a  rel="ddsubmenu4" href="<?php echo $this->baseUrl() ?>/admin/report/datewise"><b>Report</b></a>
                </li>
                 <?php if($role =='admin' || $role == 'super admin'){?>
                <li>
                    <a href="<?php echo $this->baseUrl() ?>/admin/commission"><b>Commission</b></a>
                </li>
                <li>
                    <a href="<?php echo $this->baseUrl() ?>/admin/employee"> <b>Employee</b></a>
                </li>
                 
                <li>
                    <a  rel="ddsubmenu5" href="<?php echo $this->baseUrl() ?>/admin/"><b>Systems</b></a>
                </li>
                <?php }  ?>
            </ul>
        </div>
      <?php if($role =='admin' || $role == 'super admin'){?>
            <ul id="ddsubmenu1" class="ddsubmenustyle">
                <li><a href="<?php echo $this->baseUrl() ?>/admin/prize">Price management</a></li>
                <li><a href="<?php echo $this->baseUrl() ?>/admin/bonus">Bonus management</a></li>
			</ul>
        <?php }  ?>
            <ul id="ddsubmenu2" class="ddsubmenustyle">
               <li><a href="<?php echo $this->baseUrl() ?>/admin/chitscollection/chitwise">Chit wise</a></li>
               <li><a href="<?php echo $this->baseUrl() ?>/admin/chitscollection/customerwise">Customer wise</a></li>
               <li><a href="<?php echo $this->baseUrl() ?>/admin/chitscollection/agentwise">Agent wise</a></li>
			</ul>
            <ul id="ddsubmenu3" class="ddsubmenustyle">
                <li><a href="<?php echo $this->baseUrl() ?>/admin/payment/paybill">pay bill</a></li>
            </ul>
            <ul id="ddsubmenu4" class="ddsubmenustyle">
                           <li><a href="<?php echo $this->baseUrl() ?>/admin/report/datewise">Date wise</a></li>
                           <li><a href="<?php echo $this->baseUrl() ?>/admin/report/chitwise">Chit wise</a></li>
                           <li><a href="<?php echo $this->baseUrl() ?>/admin/report/agentwise">Agent wise</a></li>
			</ul>
        <?php if($role =='admin' || $role == 'super admin'){?>
            <ul id="ddsubmenu5" class="ddsubmenustyle">
                <li><a href="<?php echo $this->baseUrl() ?>/admin/configuration">Configuration</a></li>
                <li><a href="<?php echo $this->baseUrl() ?>/admin/pincode">Pin code</a></li>
                <li><a href="<?php echo $this->baseUrl() ?>/admin/city">City</a></li>
            </ul>
        <?php }  ?>
        </div>
        <!--  start nav -->
    </div>
    <div class="clear"></div>
    <!--  start nav-outer -->
</div>
<!--  start nav-outer-repeat................................................... END -->
<div class="clear"></div>
 
<!-- start content-outer -->
<div id="content-outer">
    <!-- start content -->
    <div id="content">
        <?php echo $this->layout()->content ?>
    </div>
    <!--  end content -->
    <div class="clear">&nbsp;</div>
</div>
<!--  end content-outer -->

<div class="clear">&nbsp;</div> 
<!-- start footer -->         
<div id="footer">
    <!--  start footer-left -->
    <div id="footer-left">
        &COPY; <?=date('Y')?> All rights reserved.</div>
    <!--  end footer-left -->
    <div class="clear">&nbsp;</div>
</div>
<!-- end footer -->
 
</body>
</html>
