<?php
    $url = "{$this->baseUrl()}/admin/chitscollection/flexychitgrid";
?>
<script type="text/javascript">    
$(document).ready(function(){
    $(document).pngFix( );
    $("#flexme").flexigrid({
       url: '<?=$url?>',
       dataType: 'json',
       colModel : [
               {display: 'No', name :'id', width : 20, sortable :true, align: 'left'},
               {display: 'Chit code', name :'chit_code', width : 60, sortable :true, align: 'left'},
               {display: 'Number of Installments', name :'period', width : 30, sortable :true, align: 'left'},
               {display: 'Sala', name :'sala', width : 150,sortable : true, align: 'left'},               
               {display: 'Current Installment', name :'currentinstallment', width : 100,sortable : true, align: 'left'},               
               {display: 'Pay Date', name :'Paydate', width : 100,sortable : true, align: 'left'},        
               {display: 'Amount', name :'amount', width : 100,sortable : true, align: 'left'},         
               {display: 'Options', name :'options', width : 150,sortable : true, align: 'left'}               
           ],
	buttons : [		            
		{separator: true}
		],
        searchitems : [
            {display: 'Name', name : 'chit_code'}
            ],
       sortname: "chit_code",
       sortorder: "asc",
       usepager: true,
       title: 'Chits',
       useRp: true,
        rp: 10,
        onSubmit: addFormData,
        showTableToggleBtn: true,
        width: 700,
        height: 200
    });
     $('#chitalSearch').submit(function (){
        $('#flexme').flexOptions({newp: 1}).flexReload();
        return false;
    })
});
function addFormData(){
    //passing a form object to serializeArray will get the valid data from all the objects, but, if the you pass a non-form object, you have to specify the input elements that the data will come from
    var dt = $('#chitalSearch').serializeArray();
    $("#flexme").flexOptions({params: dt});
    return true;
}
</script>
<div id="page-heading">
		<h1>Chit Wise Payment</h1>
	</div>
<table id="flexme"></table>