<style type="text/css">
    #content{width:860px}
    legend{font-weight: bold; float: left;}
    fieldset{border: none; height: 50px; vertical-align: bottom}
    fieldset input {margin-left: 5px; float: left}
    fieldset input[type='checkbox'] {margin-top: 11px}
    
#id-form th {width:630px}
#page-heading {margin-left: 0px}

table.data{width:100%;}
table.data th{text-align: left !important;}
#total_amount-label{text-align: right !important;}
#total_amount-label label{margin-right: 30px}
</style>
<div id="page-heading"><h1>Pay Installments</h1></div>
<table class="data">
    <tr>
        <th width="250px">Name</th>
        <th width="100px">Chit Code</th>
        <th width="50px">Token</th>
        <th width="100px">Amount to pay</th>
        <th width="100px">Fine</th>
        <th>&nbsp;</th>
    </tr>
</table>
<?php echo $this->form ?>
<script>

/*
 * function for calculate the total amount to pay
 */
$(document).ready(function(){
 
        //iterate through each textboxes and add keyup
        //handler to trigger sum event
        $(".inp-amount").each(function() {
 
            $(this).keyup(function(){
                calculateSum();
            });
        });
 
    });

 function calculateSum() {
 
        var sum = 0;
        //iterate through each textboxes and add the values
        $(".inp-amount").each(function() {
 
            //add only if the value is number
            if(!isNaN(this.value) && this.value.length!=0) {
                sum += parseFloat(this.value);
            }
 
        });
        //.toFixed() method will roundoff the final sum to 2 decimal places
        $("#total_amount").val(sum.toFixed(2));
    }

</script>