<style type="text/css">
    legend{font-weight: bold; float: left;}
    fieldset{border: none; height: 50px; vertical-align: bottom}
    fieldset input {margin-left: 5px; float: left}
    fieldset input[type='checkbox'] {margin-top: 11px}
    
#id-form th {width:310px}
#page-heading {margin-left: 0px}

table.data{width:730px;}
table.data th{text-align: left !important;}
#total_amount-label, #print-label{text-align: right !important;}
#total_amount-label label, #print-label label{margin-right: 30px}
</style>
<div id="page-heading"><h1>Pay Installments</h1></div>
<table class="data">
    <tr>
        <th width="100px">Installment</th>
        <th width="120px">Amount to pay</th>
        <th width="100px">Fine</th>
        <th width="120px">Amount received</th>
        <th>Discount</th>
    </tr>
</table>
<?php echo $this->form ?>

<script>
/*
 * function for calculate the total amount to pay
 */
$(document).ready(function(){
 
        //iterate through each textboxes and add keyup
        //handler to trigger sum event
        $(".inp-amount").each(function() {
 
            $(this).keyup(function(){
                calculateSum();
            });
        });
        /*
         * 
         */
        $(".inp-discount").each(function() {
            $(this).keyup(function(){
               // calculateSum();
               str = this.id;
               id = str.replace("di_", "")              
               total_amount = parseInt($('#fine_'+id).val()) + parseInt($('#hd_amount_'+id).val()); 
               $('#am_'+id).val(total_amount);
               $('#am_'+id).val( $('#am_'+id).val() - $('#di_'+id).val());                                  
               calculateSum();
            });
        });
 
    });

 function calculateSum() {
 
        var sum = 0;
        var discount = 0;
        var total = 0;
        //iterate through each textboxes and add the values
        $(".inp-amount").each(function() {
 
            //add only if the value is number
            if(!isNaN(this.value) && this.value.length!=0) {
                sum += parseFloat(this.value);
            }
 
        });        
        //.toFixed() method will roundoff the final sum to 2 decimal places
        $("#total_amount").val(sum.toFixed(2));
    }

</script>