<script type="text/javascript">
    function checkUser()
    {
        //alert('jjj');
        var str = 'Is It You \n';
        str += '-------------------\n';
        $.ajax({
            type: "POST",
            url: '<?php echo $this->baseUrl() ?>/admin/users/checkuser',
            data: {first_name: $('#first_name').val(), house_name: $('#house_name').val()},
            dataType: 'json',
            success: function(response){
                if(response.data == 'true') {
                    $.each(response, function(key, val) {
                        if(key != 'data') {
                            str += ucfirst(key.replace("_", " ")) + ' : ' + val + '\n';
                        }
                    });
                    str += '-------------------\n';
                    var r=confirm(str);
                    if (r==true){
                        window.location.href = "<?php echo $this->baseUrl() ?>/admin/users";
                    }
                }
                
            }
        });
    }
    function ucfirst(string)
    {
        return string.charAt(0).toUpperCase() + string.slice(1);
    }

</script>
<div id="page-heading"><h1>Add User</h1></div>


<table width="100%" cellspacing="0" cellpadding="0" border="0" id="content-table">
<tbody><tr>
	<th class="sized" rowspan="3"><img width="20" height="300" alt="" src="images/shared/side_shadowleft.jpg"></th>
	<th class="topleft"></th>
	<td id="tbl-border-top">&nbsp;</td>
	<th class="topright"></th>
	<th class="sized" rowspan="3"><img width="20" height="300" alt="" src="images/shared/side_shadowright.jpg"></th>
</tr>
<tr>
	<td id="tbl-border-left"></td>
	<td>
	<!--  start content-table-inner -->
	<div id="content-table-inner">
	
	<?php echo $this->userForm; ?>
 
<div class="clear"></div>
 

</div>
<!--  end content-table-inner  -->
</td>
<td id="tbl-border-right"></td>
</tr>
<tr>
	<th class="sized bottomleft"></th>
	<td id="tbl-border-bottom">&nbsp;</td>
	<th class="sized bottomright"></th>
</tr>
</tbody></table>

<div class="clear">&nbsp;</div>
